/** Module name pytest loads with `-p`; the file lives in the feature's data folder. */
export const PLUGIN_MODULE = 'anvil_pytest_reporter';

/** Prefix of every reporter line, so they can be told apart from the tests' own output. */
export const REPORT_MARK = '@@anvil-pytest ';

/**
 * A tiny pytest plugin (written to disk and loaded with `-p` + PYTHONPATH, so the user's project
 * needs no conftest). It changes nothing about collection or running; it only prints one JSON line
 * per collected item and per test report, with the real file and line of each test.
 *
 * It writes to a duplicate of the original stdout taken at import time: `-p` plugins are imported
 * before pytest starts capturing, so the lines get out even while a test's output is captured.
 * A line can land after pytest's progress dots (which have no newline yet), so the reader looks for
 * the mark anywhere in a line. JSON is ASCII-only so a Windows code page can't mangle it.
 */
export const PLUGIN_SOURCE = `"""Anvil's pytest reporter. Generated by Anvil; safe to delete."""
import json
import os
import sys

_MARK = ${JSON.stringify(REPORT_MARK)}

try:
    _FD = os.dup(sys.stdout.fileno())
except Exception:
    _FD = None


def _emit(record):
    line = _MARK + json.dumps(record, ensure_ascii=True) + "\\n"
    data = line.encode("ascii")
    if _FD is not None:
        os.write(_FD, data)
    else:
        sys.__stdout__.write(line)
        sys.__stdout__.flush()


def _path(node):
    path = getattr(node, "path", None)
    return str(path if path is not None else node.fspath)


def _line(node):
    try:
        lineno = node.reportinfo()[1]
    except Exception:
        return None
    return lineno + 1 if isinstance(lineno, int) else None


def _classes(item):
    out = []
    parent = item.parent
    while parent is not None and type(parent).__name__ == "Class":
        out.append({"nodeid": parent.nodeid, "line": _line(parent)})
        parent = parent.parent
    out.reverse()
    return out


def pytest_collection_finish(session):
    for item in session.items:
        line = item.location[1]
        _emit({
            "t": "item",
            "nodeid": item.nodeid,
            "file": _path(item),
            "line": line + 1 if isinstance(line, int) else None,
            "classes": _classes(item),
        })
    _emit({"t": "collected", "count": len(session.items)})


def pytest_collectreport(report):
    if report.failed:
        _emit({"t": "collecterror", "nodeid": report.nodeid, "message": str(report.longrepr)})


def pytest_runtest_logstart(nodeid, location):
    _emit({"t": "start", "nodeid": nodeid})


def _crash(report):
    crash = getattr(report.longrepr, "reprcrash", None)
    if crash is None or not isinstance(getattr(crash, "lineno", None), int):
        return None
    return {"path": str(crash.path), "line": max(crash.lineno, 1)}


def pytest_runtest_logreport(report):
    xfail = hasattr(report, "wasxfail")
    if report.when == "call":
        outcome = report.outcome
    elif report.failed:
        outcome = "error"
    elif report.skipped and report.when == "setup":
        outcome = "skipped"
    else:
        # A passing setup or teardown only adds to the duration.
        _emit({"t": "phase", "nodeid": report.nodeid, "duration": report.duration})
        return
    message = None
    text = None
    if outcome == "skipped":
        if xfail:
            message = "xfail: " + str(report.wasxfail) if report.wasxfail else "xfail"
        elif isinstance(report.longrepr, tuple) and len(report.longrepr) == 3:
            message = str(report.longrepr[2])
    elif outcome in ("failed", "error"):
        text = report.longreprtext
        crash = getattr(report.longrepr, "reprcrash", None)
        message = str(getattr(crash, "message", "")) or (text.strip().splitlines() or [""])[-1]
    elif xfail:
        message = "xpass"
    _emit({
        "t": "result",
        "nodeid": report.nodeid,
        "outcome": outcome,
        "when": report.when,
        "duration": report.duration,
        "message": message,
        "longrepr": text,
        "crash": _crash(report) if outcome in ("failed", "error") else None,
    })


def pytest_sessionfinish(session, exitstatus):
    _emit({"t": "done", "exitstatus": int(exitstatus)})
`;
