import { useQuery } from '@tanstack/react-query';
import { ImageOff, RotateCw, Scan, ZoomIn, ZoomOut } from 'lucide-react';
import {
	type JSX,
	type KeyboardEvent,
	type PointerEvent,
	type RefObject,
	useCallback,
	useEffect,
	useRef,
	useState,
} from 'react';

import { cn } from '../../lib/cn';
import { call } from '../../lib/ipc';
import { useAnvilEvent } from '../../lib/use-anvil-event';
import { Button } from '../../ui/Button';
import { EmptyState } from '../../ui/EmptyState';
import { ErrorState } from '../../ui/ErrorState';
import { IconButton } from '../../ui/IconButton';
import { Spinner } from '../../ui/Spinner';
import { Tooltip } from '../../ui/Tooltip';
import { ReloadErrorBadge } from './ReloadErrorBadge';
import { baseName, formatBytes } from './viewer-paths';

import './viewers.css';

const MIN_SCALE = 0.05;
const MAX_SCALE = 32;
const STEP = 1.25;
const PAN_STEP = 60;

interface Point {
	x: number;
	y: number;
}

type Zoom = 'fit' | number;

function clampScale(scale: number): number {
	return Math.min(MAX_SCALE, Math.max(MIN_SCALE, scale));
}

/** Tracks an element's content size so "fit" follows pane resizes and splits. */
function useSize(ref: RefObject<HTMLElement | null>): { w: number; h: number } {
	const [size, setSize] = useState({ w: 0, h: 0 });
	useEffect(() => {
		const el = ref.current;
		if (!el) return;
		const observer = new ResizeObserver(([entry]) => {
			if (entry) setSize({ w: entry.contentRect.width, h: entry.contentRect.height });
		});
		observer.observe(el);
		return () => observer.disconnect();
	}, [ref]);
	return size;
}

export function ImageViewer({ path }: { path: string }): JSX.Element {
	const query = useQuery({
		queryKey: ['fs-image', path],
		queryFn: () => call('fs:readDataUrl', path),
	});
	const { refetch } = query;
	// Plots regenerated by a running training script should update in place.
	useAnvilEvent('fs:changed', ({ files }) => {
		if (files.includes(path)) void refetch();
	});

	const viewport = useRef<HTMLDivElement>(null);
	const view = useSize(viewport);
	const [natural, setNatural] = useState<{ w: number; h: number } | null>(null);
	const [decodeError, setDecodeError] = useState(false);
	const [zoom, setZoom] = useState<Zoom>('fit');
	const [offset, setOffset] = useState<Point>({ x: 0, y: 0 });
	const drag = useRef<{ start: Point; origin: Point } | null>(null);
	const [dragging, setDragging] = useState(false);

	const fitScale =
		natural && view.w > 0 && view.h > 0
			? Math.min(1, (view.w - 32) / natural.w, (view.h - 32) / natural.h)
			: 1;
	const scale = zoom === 'fit' ? Math.max(MIN_SCALE, fitScale) : zoom;
	const width = (natural?.w ?? 0) * scale;
	const height = (natural?.h ?? 0) * scale;
	const pannable = width > view.w || height > view.h;

	// Keep the image covering the viewport instead of letting it drift off-screen.
	const clampOffset = useCallback(
		(p: Point, w = width, h = height): Point => {
			const maxX = Math.max(0, (w - view.w) / 2);
			const maxY = Math.max(0, (h - view.h) / 2);
			return {
				x: Math.min(maxX, Math.max(-maxX, p.x)),
				y: Math.min(maxY, Math.max(-maxY, p.y)),
			};
		},
		[width, height, view.w, view.h],
	);

	/** Zooms keeping the point under `anchor` (relative to the viewport centre) fixed. */
	const zoomTo = useCallback(
		(next: Zoom, anchor: Point = { x: 0, y: 0 }) => {
			if (next === 'fit' || !natural) {
				setZoom(next);
				setOffset({ x: 0, y: 0 });
				return;
			}
			const target = clampScale(next);
			const ratio = target / scale;
			setZoom(target);
			setOffset((raw) => {
				const prev = clampOffset(raw);
				return clampOffset(
					{
						x: anchor.x - (anchor.x - prev.x) * ratio,
						y: anchor.y - (anchor.y - prev.y) * ratio,
					},
					natural.w * target,
					natural.h * target,
				);
			});
		},
		[natural, scale, clampOffset],
	);

	// React registers wheel listeners as passive, so Ctrl+wheel needs a native listener to stop
	// the whole window from zooming.
	useEffect(() => {
		const el = viewport.current;
		if (!el) return;
		const onWheel = (event: WheelEvent): void => {
			if (event.ctrlKey || event.metaKey) {
				event.preventDefault();
				const rect = el.getBoundingClientRect();
				const anchor = {
					x: event.clientX - rect.left - rect.width / 2,
					y: event.clientY - rect.top - rect.height / 2,
				};
				zoomTo(scale * Math.exp(-event.deltaY * 0.0015), anchor);
			} else if (pannable) {
				event.preventDefault();
				setOffset((raw) => {
					const prev = clampOffset(raw);
					return clampOffset({
						x: prev.x - (event.shiftKey ? event.deltaY : event.deltaX),
						y: prev.y - (event.shiftKey ? 0 : event.deltaY),
					});
				});
			}
		};
		el.addEventListener('wheel', onWheel, { passive: false });
		return () => el.removeEventListener('wheel', onWheel);
	}, [zoomTo, scale, pannable, clampOffset]);

	// Clamped at render so pane resizes or a regenerated plot never leave the image off-screen.
	const pos = clampOffset(offset);

	const onPointerDown = (event: PointerEvent<HTMLDivElement>): void => {
		if (!pannable || event.button !== 0) return;
		event.currentTarget.setPointerCapture(event.pointerId);
		drag.current = { start: { x: event.clientX, y: event.clientY }, origin: pos };
		setDragging(true);
	};
	const onPointerMove = (event: PointerEvent<HTMLDivElement>): void => {
		const d = drag.current;
		if (!d) return;
		setOffset(
			clampOffset({
				x: d.origin.x + event.clientX - d.start.x,
				y: d.origin.y + event.clientY - d.start.y,
			}),
		);
	};
	const endDrag = (): void => {
		drag.current = null;
		setDragging(false);
	};

	// Handled on the whole viewer, not just the image pane, so the advertised shortcuts keep
	// working after a toolbar button was clicked (focus stays on the button).
	const onKeyDown = (event: KeyboardEvent<HTMLDivElement>): void => {
		if (event.ctrlKey || event.altKey || event.metaKey) return;
		if (event.target instanceof HTMLInputElement || event.target instanceof HTMLTextAreaElement)
			return;
		const pan = (dx: number, dy: number): void =>
			setOffset(clampOffset({ x: pos.x + dx, y: pos.y + dy }));
		const actions: Record<string, () => void> = {
			'+': () => zoomTo(scale * STEP),
			'=': () => zoomTo(scale * STEP),
			'-': () => zoomTo(scale / STEP),
			'0': () => zoomTo('fit'),
			'1': () => zoomTo(1),
			ArrowLeft: () => pan(PAN_STEP, 0),
			ArrowRight: () => pan(-PAN_STEP, 0),
			ArrowUp: () => pan(0, PAN_STEP),
			ArrowDown: () => pan(0, -PAN_STEP),
		};
		const action = actions[event.key];
		if (action) {
			event.preventDefault();
			action();
		}
	};

	const data = query.data;
	let stage: JSX.Element | null = null;
	if (query.isPending) {
		stage = <Spinner size={24} label='Loading image' />;
	} else if (query.isError && !data) {
		stage = (
			<ErrorState
				title='Could not open image'
				message={query.error.message}
				onRetry={() => void refetch()}
			/>
		);
	} else if (data && data.size === 0) {
		stage = (
			<EmptyState
				icon={<ImageOff size={24} />}
				title='Empty file'
				description='0 bytes on disk.'
			/>
		);
	} else if (decodeError) {
		stage = (
			<ErrorState
				title='Could not decode image'
				message='The file is corrupt or in a format Chromium cannot display.'
				onRetry={() => {
					setDecodeError(false);
					void refetch();
				}}
			/>
		);
	}

	return (
		<div className='flex h-full min-h-0 flex-col' onKeyDown={onKeyDown}>
			<div className='flex h-9 shrink-0 items-center gap-3 border-b border-glass-edge px-3'>
				<span className='hud'>Image</span>
				<span className='truncate text-12 text-fg-1'>{baseName(path)}</span>
				{natural && (
					<span className='hud num text-fg-1'>
						{natural.w}×{natural.h}
					</span>
				)}
				{data && <span className='hud num'>{formatBytes(data.size)}</span>}
				{query.isError && data && <ReloadErrorBadge message={query.error.message} />}
				<span className='flex-1' />
				{query.isFetching && !query.isPending && <Spinner size={12} label='Refreshing' />}
				<IconButton
					size='sm'
					label='Zoom out'
					shortcut='-'
					icon={<ZoomOut size={14} />}
					disabled={!natural}
					onClick={() => zoomTo(scale / STEP)}
				/>
				<Tooltip content='Zoom level'>
					<span className='hud num w-12 text-center text-fg-0'>
						{Math.round(scale * 100)}%
					</span>
				</Tooltip>
				<IconButton
					size='sm'
					label='Zoom in'
					shortcut='='
					icon={<ZoomIn size={14} />}
					disabled={!natural}
					onClick={() => zoomTo(scale * STEP)}
				/>
				<IconButton
					size='sm'
					label='Fit to pane'
					shortcut='0'
					icon={<Scan size={14} />}
					active={zoom === 'fit'}
					disabled={!natural}
					onClick={() => zoomTo('fit')}
				/>
				<Tooltip content='Actual size' shortcut='1'>
					<Button
						size='sm'
						variant='ghost'
						aria-pressed={zoom === 1}
						disabled={!natural}
						className={cn('num', zoom === 1 && 'bg-accent-soft text-accent')}
						onClick={() => zoomTo(1)}
					>
						1:1
					</Button>
				</Tooltip>
				<IconButton
					size='sm'
					label='Reload from disk'
					icon={<RotateCw size={14} />}
					onClick={() => void refetch()}
				/>
			</div>
			<div
				ref={viewport}
				tabIndex={0}
				role='img'
				aria-label={`${baseName(path)}${natural ? `, ${natural.w} by ${natural.h} pixels` : ''}`}
				className={cn(
					'relative min-h-0 flex-1 overflow-hidden focus-visible:-outline-offset-1',
					pannable && (dragging ? 'cursor-grabbing' : 'cursor-grab'),
				)}
				onPointerDown={onPointerDown}
				onPointerMove={onPointerMove}
				onPointerUp={endDrag}
				onPointerCancel={endDrag}
				onDoubleClick={() => zoomTo(zoom === 'fit' ? 1 : 'fit')}
			>
				{stage ? (
					<div className='flex h-full items-center justify-center'>{stage}</div>
				) : (
					data && (
						<div
							className='checkerboard absolute top-1/2 left-1/2 rounded-sm shadow-panel outline outline-glass-edge'
							style={{
								width,
								height,
								transform: `translate(calc(-50% + ${pos.x}px), calc(-50% + ${pos.y}px))`,
								visibility: natural ? 'visible' : 'hidden',
							}}
						>
							<img
								src={data.url}
								alt=''
								draggable={false}
								className='block size-full'
								// Pixel-level zoom on small plots should show pixels, not blur.
								style={{ imageRendering: scale >= 2 ? 'pixelated' : 'auto' }}
								onLoad={(e) => {
									setDecodeError(false);
									// SVGs without width/height report 0; use the CSS default box.
									setNatural({
										w: e.currentTarget.naturalWidth || 300,
										h: e.currentTarget.naturalHeight || 150,
									});
								}}
								onError={() => setDecodeError(true)}
							/>
						</div>
					)
				)}
				{!stage && !natural && data && (
					<div className='absolute inset-0 flex items-center justify-center'>
						<Spinner size={24} label='Decoding image' />
					</div>
				)}
			</div>
		</div>
	);
}
