import type { PixelArt } from './pixel';

/* Pixel art for tools, files and the app itself (see pixel.ts for the character key). */

export const ROBOT: PixelArt = [
	'.......rr.......',
	'.......kk.......',
	'.......kk.......',
	'..kkkkkkkkkkkk..',
	'.kwwwwwwwwwwwwk.',
	'.kwskksssskksgk.',
	'kkwkaaksskaakgkk',
	'kkwkaaksskaakgkk',
	'kkwskksssskksgkk',
	'.kwssssssssssgk.',
	'.kwskkkkkkkssgk.',
	'.kwskwkwkwkssgk.',
	'.kwskkkkkkkssgk.',
	'.kggggggggggggk.',
	'..kkkkkkkkkkkk..',
	'................',
];

export const SLIDERS: PixelArt = [
	'................',
	'..k....k....k...',
	'..k....k..kkkkk.',
	'..k....k..kwbbk.',
	'..k....k..kkkkk.',
	'kkkkk..k....k...',
	'kwrrk..k....k...',
	'kkkkk..k....k...',
	'..k....k....k...',
	'..k..kkkkk..k...',
	'..k..kweek..k...',
	'..k..kkkkk..k...',
	'..k....k....k...',
	'..k....k....k...',
	'................',
	'................',
];

export const PROMPT: PixelArt = [
	'kkkkkkkkkkkkkkkk',
	'knnnnnnnnnnnnnnk',
	'kssssssssssssssk',
	'kskkkkkkkkkkkksk',
	'kskkwwkkkkkkkksk',
	'kskwkkkwkkkkkksk',
	'kskwkkkkwkkkkksk',
	'kskwkkkwkkkkkksk',
	'kskkwwkkkkwwwksk',
	'kskkkkkkkkkkkksk',
	'kskkkkkkkkkkkksk',
	'kskkkkkkkkkkkksk',
	'kskkkkkkkkkkkksk',
	'kssssssssssssssk',
	'kggggggggggggggk',
	'kkkkkkkkkkkkkkkk',
];

export const WARNING: PixelArt = [
	'.......kk.......',
	'......kyyk......',
	'......kyyk......',
	'.....kyyyyk.....',
	'.....kykkyk.....',
	'....kyykkyyk....',
	'....kyykkyyk....',
	'...kyyykkyyyk...',
	'...kyyykkyyyk...',
	'..kyyyykkyyyyk..',
	'..kyyyyyyyyyyk..',
	'.kyyyyykkyyyyyk.',
	'.kyyyyykkyyyyyk.',
	'kyyyyyyyyyyyyyyk',
	'kkkkkkkkkkkkkkkk',
	'................',
];

export const PLAY: PixelArt = [
	'................',
	'....kk..........',
	'....kek.........',
	'....klek........',
	'....kleek.......',
	'....kleeek......',
	'....kleeeek.....',
	'....kleeeeek....',
	'....kleeeeek....',
	'....kleeeek.....',
	'....kleeek......',
	'....kleek.......',
	'....klek........',
	'....kek.........',
	'....kk..........',
	'................',
];

export const PAINT: PixelArt = [
	'................',
	'....kkkkkk......',
	'..kkhhhhhhkk....',
	'.khhrrhhbbhhk...',
	'.khhrrhhbbhhhk..',
	'khhhhhhhhhhhhhk.',
	'khyyhhhhhhhheehk',
	'khyyhhhkkhhheehk',
	'khhhhhhkkhhhhhk.',
	'khhhhhhhhhhhhk..',
	'.khhhhhhhhhhk...',
	'..kkhhhhhkkk....',
	'....kkkkk.......',
	'................',
	'................',
	'................',
];

export const ANVIL: PixelArt = [
	'..........y..y..',
	'...........yy...',
	'..........yywyy.',
	'...........yy...',
	'...kkkkkkkkkkkk.',
	'.kkkwwwwwwwwwwsk',
	'kssssssssssssssk',
	'.kkkgsssssssssgk',
	'....kkgssssgkk..',
	'......kgsssgk...',
	'......kgsssgk...',
	'....kkgssssskk..',
	'...kgggggggggk..',
	'...kkkkkkkkkkk..',
	'................',
	'................',
];

export const DOCUMENT: PixelArt = [
	'..kkkkkkkk......',
	'..kwwwwwwkk.....',
	'..kwwwwwwksk....',
	'..kwwwwwwkkkk...',
	'..kwwwwwwwwwk...',
	'..kwggggggwwk...',
	'..kwwwwwwwwwk...',
	'..kwgggggggwk...',
	'..kwwwwwwwwwk...',
	'..kwggggggwwk...',
	'..kwwwwwwwwwk...',
	'..kwgggggggwk...',
	'..kwwwwwwwwwk...',
	'..kkkkkkkkkkk...',
	'................',
	'................',
];

export const NEW_DOCUMENT: PixelArt = [
	'..kkkkkkkk...y..',
	'..kwwwwwwkk.yyy.',
	'..kwwwwwwksk.y..',
	'..kwwwwwwkkkk...',
	'..kwwwwwwwwwk...',
	'..kwwwwwwwwwk...',
	'..kwwwwwwwwwk...',
	'..kwwwwwwwwwk...',
	'..kwwwwwwwwwk...',
	'..kwwwwwwwwwk...',
	'..kwwwwwwwwwk...',
	'..kwwwwwwwwwk...',
	'..kwwwwwwwwwk...',
	'..kkkkkkkkkkk...',
	'................',
	'................',
];

export const OPEN_FOLDER: PixelArt = [
	'................',
	'................',
	'.kkkkk..........',
	'kwyyyyk.........',
	'koooooookkkkkk..',
	'kooooooooooook..',
	'kooookkkkkkkkkkk',
	'koookyyyyyyyyyk.',
	'kookyyyyyyyyyk..',
	'kookyyyyyyyyyk..',
	'kokyyyyyyyyyk...',
	'kkyyyyyyyyyk....',
	'kkkkkkkkkkk.....',
	'................',
	'................',
	'................',
];

export const FLOPPY: PixelArt = [
	'kkkkkkkkkkkkkkk.',
	'knnksssksknnnnk.',
	'knnksssksknnnnk.',
	'knnksssksknnnnk.',
	'knnkkkkkkknnnnk.',
	'knnnnnnnnnnnnnk.',
	'knnnnnnnnnnnnnk.',
	'knkkkkkkkkkkknk.',
	'knkwwwwwwwwwknk.',
	'knkwgggggggwknk.',
	'knkwwwwwwwwwknk.',
	'knkwgggggggwknk.',
	'knkwwwwwwwwwknk.',
	'kkkkkkkkkkkkkkk.',
	'................',
	'................',
];
