import type { PixelArt } from './pixel';

/* Pixel art for the side views (see pixel.ts for the character key). */

export const FOLDER: PixelArt = [
	'................',
	'................',
	'..kkkkk.........',
	'.kwyyyyk........',
	'kwyyyyyykkkkkkk.',
	'kwwwwwwwwwwwwwyk',
	'kwyyyyyyyyyyyyok',
	'kwyyyyyyyyyyyyok',
	'kwyyyyyyyyyyyyok',
	'kwyyyyyyyyyyyyok',
	'kwyyyyyyyyyyyyok',
	'kwyyyyyyyyyyyyok',
	'kwyyyyyyyyyyyyok',
	'kooooooooooooook',
	'kkkkkkkkkkkkkkkk',
	'................',
];

export const MAGNIFIER: PixelArt = [
	'................',
	'....kkkkk.......',
	'...kwwaaak......',
	'..kwaaaaaak.....',
	'..kwaaaaaak.....',
	'..kaaaaaaak.....',
	'..kaaaaaaak.....',
	'..kaaaaaaak.....',
	'...kaaaaak......',
	'....kkkkkgg.....',
	'.........kgg....',
	'..........kgg...',
	'...........kgg..',
	'............kgk.',
	'.............kk.',
	'................',
];

export const BRANCH: PixelArt = [
	'................',
	'..kkk......kkk..',
	'.keeek....kbbbk.',
	'.keeek....kbbbk.',
	'.keeek....kbbbk.',
	'..kkk......kkk..',
	'...k........k...',
	'...k.......k....',
	'...k......k.....',
	'...k.....k......',
	'...k....k.......',
	'...k..kk........',
	'..kkkk..........',
	'.keeek..........',
	'.keeek..........',
	'..kkk...........',
];

export const PROGRAM: PixelArt = [
	'kkkkkkkkkkkkkkkk',
	'knnnnnnnnnnnnnnk',
	'kkkkkkkkkkkkkkkk',
	'kwwwwwwwwwwwwwsk',
	'kwwwwkkwwwwwwwsk',
	'kwwwwkekkwwwwwsk',
	'kwwwwkeeekkwwwsk',
	'kwwwwkeeeeekkwsk',
	'kwwwwkeeeeeekwsk',
	'kwwwwkeeeeekkwsk',
	'kwwwwkeeekkwwwsk',
	'kwwwwkekkwwwwwsk',
	'kwwwwkkwwwwwwwsk',
	'kwwwwwwwwwwwwwsk',
	'kssssssssssssssk',
	'kkkkkkkkkkkkkkkk',
];

export const TREE: PixelArt = [
	'................',
	'.kkkkk..........',
	'.kyyyk.kkkkkkkk.',
	'.kyyyk..........',
	'.kkkkk..........',
	'...k............',
	'...k..kkkk......',
	'...kkkkbbk.kkkkk',
	'...k..kkkk......',
	'...k............',
	'...k..kkkk......',
	'...kkkkeek.kkkkk',
	'......kkkk......',
	'................',
	'................',
	'................',
];

export const CHECKLIST: PixelArt = [
	'................',
	'.kkkkkkkkkkkkk..',
	'.kwwwwwwwwwwwk..',
	'.kwkkkwwwwwwwk..',
	'.kwkekwkkkkkwk..',
	'.kwkkkwwwwwwwk..',
	'.kwwwwwwwwwwwk..',
	'.kwkkkwwwwwwwk..',
	'.kwkekwkkkkkwk..',
	'.kwkkkwwwwwwwk..',
	'.kwwwwwwwwwwwk..',
	'.kwkkkwwwwwwwk..',
	'.kwkwkwkkkkkwk..',
	'.kwkkkwwwwwwwk..',
	'.kkkkkkkkkkkkk..',
	'................',
];

export const CLOCK: PixelArt = [
	'................',
	'.....kkkkkk.....',
	'...kkwwwwwwkk...',
	'..kwwwwkwwwwwk..',
	'.kwwwwwkwwwwwwk.',
	'.kwwwwwkwwwwwwk.',
	'kwwwwwwkwwwwwwwk',
	'kwkwwwwkwwwwwkwk',
	'kwwwwwwkrrrrwwwk',
	'kwwwwwwwwwwwwwwk',
	'.kwwwwwwwwwwwwk.',
	'.kwwwwwwwwwwwwk.',
	'..kwwwwkwwwwwk..',
	'...kkwwwwwwkk...',
	'.....kkkkkk.....',
	'................',
];

export const BLOCKS: PixelArt = [
	'................',
	'................',
	'....kkkkkkk.....',
	'....krrrrrk.....',
	'....krwrrrk.....',
	'....krrrrrk.....',
	'....krrrrrk.....',
	'....krrrrrk.....',
	'kkkkkkkkkkkkkkk.',
	'kbbbbbbkeeeeeek.',
	'kbwbbbbkeweeeek.',
	'kbbbbbbkeeeeeek.',
	'kbbbbbbkeeeeeek.',
	'kbbbbbbkeeeeeek.',
	'kkkkkkkkkkkkkkk.',
	'................',
];

export const TOOLBOX: PixelArt = [
	'................',
	'................',
	'.....kkkkkk.....',
	'....kk....kk....',
	'....k......k....',
	'.kkkkkkkkkkkkkk.',
	'krwrrrrrrrrrrrmk',
	'krrrrrrrrrrrrrmk',
	'kkkkkkksskkkkkkk',
	'krrrrrksskrrrrmk',
	'krrrrrrkkrrrrrmk',
	'krrrrrrrrrrrrrmk',
	'krrrrrrrrrrrrrmk',
	'kmmmmmmmmmmmmmmk',
	'kkkkkkkkkkkkkkkk',
	'................',
];
