"""
Writes src/renderer/styles/fonts.css: @font-face rules for every bundled font, woff2 only.

The @fontsource stylesheets also list .woff fallbacks, which Chromium never uses but Vite
would still copy into the build. Run after adding a font: python scripts/gen_fonts.py
"""

import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / 'src' / 'renderer' / 'styles' / 'fonts.css'

# (package, stylesheet names under @fontsource/<package>/)
FONTS: list[tuple[str, list[str]]] = [
	# UI and code (Cyber Glass and shared)
	('geist-sans', ['latin-400', 'latin-500', 'latin-600', 'latin-700']),
	('jetbrains-mono', ['latin-400', 'latin-500', 'latin-700', 'latin-400-italic']),
	('fira-code', ['latin-400', 'latin-700']),
	('geist-mono', ['latin-400', 'latin-700', 'latin-400-italic']),
	('ibm-plex-mono', ['latin-400', 'latin-700', 'latin-400-italic']),
	('victor-mono', ['latin-400', 'latin-700', 'latin-400-italic']),
	('cascadia-code', ['latin-400', 'latin-700', 'latin-400-italic']),
	('monaspace-neon', ['latin-400', 'latin-700', 'latin-400-italic']),
	('maple-mono', ['latin-400', 'latin-700', 'latin-400-italic']),
	('iosevka', ['latin-400', 'latin-700', 'latin-400-italic']),
	('space-mono', ['latin-400', 'latin-700']),
	('share-tech-mono', ['latin-400']),
	('vt323', ['latin-400']),
	# Skin UI and display fonts
	('inter-tight', ['latin-400', 'latin-500', 'latin-700']),
	('space-grotesk', ['latin-400', 'latin-500', 'latin-700']),
	('archivo-black', ['latin-400']),
	('bebas-neue', ['latin-400']),
	('ibm-plex-sans-condensed', ['latin-400', 'latin-500', 'latin-700']),
	('big-shoulders-display', ['latin-700', 'latin-900']),
	('pixelify-sans', ['latin-400', 'latin-700']),
	('silkscreen', ['latin-400', 'latin-700']),
	('tiny5', ['latin-400']),
	('orbitron', ['latin-500', 'latin-700', 'latin-900']),
	('rajdhani', ['latin-500', 'latin-600', 'latin-700']),
	('chakra-petch', ['latin-400', 'latin-600']),
	('newsreader', ['latin-400', 'latin-600', 'latin-400-italic']),
	('instrument-serif', ['latin-400', 'latin-400-italic']),
	('fraunces', ['latin-400', 'latin-600', 'latin-700']),
	('nunito', ['latin-400', 'latin-700', 'latin-800']),
	('baloo-2', ['latin-500', 'latin-700', 'latin-800']),
	('comfortaa', ['latin-400', 'latin-700']),
]


def faces(package: str, sheet: str) -> list[str]:
	css = (ROOT / 'node_modules' / '@fontsource' / package / f'{sheet}.css').read_text('utf-8')
	out = []
	for block in re.findall(r'@font-face \{.*?\}', css, flags=re.S):
		file = re.search(r'url\(\./files/([^)]+?\.woff2)\)', block)
		family = re.search(r"font-family: '([^']+)'", block)
		style = re.search(r'font-style: (\w+)', block)
		weight = re.search(r'font-weight: (\d+)', block)
		if not (file and family and style and weight):
			raise SystemExit(f'unexpected @font-face in {package}/{sheet}.css')
		rules = [
			f"\tfont-family: '{family.group(1)}';",
			f'\tfont-style: {style.group(1)};',
			'\tfont-display: swap;',
			f'\tfont-weight: {weight.group(1)};',
			f"\tsrc: url('../../../node_modules/@fontsource/{package}/files/{file.group(1)}')",
			"\t\tformat('woff2');",
		]
		unicode_range = re.search(r'unicode-range: ([^;]+);', block)
		if unicode_range:
			rules.append(f'\tunicode-range: {unicode_range.group(1)};')
		out.append('@font-face {\n' + '\n'.join(rules) + '\n}')
	return out


def main() -> None:
	header = (
		'/*\n'
		' * Bundled fonts, woff2 only. Generated by scripts/gen_fonts.py; edit the list there.\n'
		' * A font file downloads only when something on screen uses that family.\n'
		' */\n'
	)
	blocks = [face for package, sheets in FONTS for sheet in sheets for face in faces(package, sheet)]
	OUT.write_text(header + '\n' + '\n'.join(blocks) + '\n', encoding='utf-8', newline='\n')
	print(f'{len(blocks)} faces -> {OUT.relative_to(ROOT)}')


if __name__ == '__main__':
	main()
